### ISSUE TITLE
Nuget or Xamarin component

### ISSUE THREAD

**Issue by has-taiar** [TheEightBot/Xamarin.IQKeyboardManager#1]
Thanks heaps for this great piece, 
This is not really an issue, but rather a suggestion, do you plan on publishing this as a Nuget package or a xamarin component? Happy to help out in setting that up. I believe many Devs could benefit from it by just grabbing it quickly from Xamarin store or the Nuget package server

**Comment by qqilihq** [comment]
Agree, I would really love to see this available as Xamarin component.

**Comment by michaelstonis** [comment]
The library is now available on nuget [here](https://www.nuget.org/packages/Xamarin.IQKeyboardManager/)
