### ISSUE TITLE
iOS 11 compatibility

### ISSUE THREAD

**Issue by squale** [TheEightBot/Xamarin.IQKeyboardManager#10]
Can you please sync and update to at least version 4.0.13,
 it fixes an [issue with iOS 11](https://github.com/hackiftekhar/IQKeyboardManager/commit/74b64a167738afdfb319ae0613409cb5c2afd86b)

Thanks in advance

**Comment by michaelstonis** [comment]
I was able to get the new version of ObjectiveSharpie and kick out a release this afternoon against the latest version of IQKeyboardManager
