### ISSUE TITLE
Native linking is failing on iPhone builds

### ISSUE THREAD

**Issue by eman1986** [TheEightBot/Xamarin.IQKeyboardManager#14]
When I do a device build I get the following errors:

> error MT5209 : Native linking error : warning: ignoring file /Users/vsts/agent/2.150.3/work/1/s/MyApp/iOS/obj/iPhone/Debug/mtouch-cache/IQKeyboardManager.framework/IQKeyboardManager, missing required architecture armv7s in file /Users/vsts/agent/2.150.3/work/1/s/MyApp/iOS/obj/iPhone/Debug/mtouch-cache/IQKeyboardManager.framework/IQKeyboardManager (4 slices)
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQBarButtonItem. The symbol '_OBJC_CLASS_$_IQBarButtonItem' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQKeyboardManager. The symbol '_OBJC_CLASS_$_IQKeyboardManager' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQKeyboardReturnKeyHandler. The symbol '_OBJC_CLASS_$_IQKeyboardReturnKeyHandler' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQPreviousNextView. The symbol '_OBJC_CLASS_$_IQPreviousNextView' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQTextView. The symbol '_OBJC_CLASS_$_IQTextView' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQTitleBarButtonItem. The symbol '_OBJC_CLASS_$_IQTitleBarButtonItem' could not be found in any of the libraries or frameworks linked with your application.
> MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: IQToolbar. The symbol '_OBJC_CLASS_$_IQToolbar' could not be found in any of the libraries or frameworks linked with your application.

How do I overcome this issue?

**Comment by michaelstonis** [comment]
Remove the armv7s from a build target. iOS apps pretty much should be arm64 at this point in time.

![VisualStudio 2019-05-15 13-22-19](https://user-images.githubusercontent.com/120685/57799444-b880a280-7714-11e9-9ee4-1beb7b5ae6f3.png)
