### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Anhnh** [TheEightBot/Xamarin.IQKeyboardManager#2]
I'm a beginning xamarin developer. Anyone help me how to add Xamarin.IQKeyboardManager into my project.
Thank you!

**Comment by vecalion** [comment]
There is a sample project demonstrating how to use Xamarin.IQKeyboardManager: https://github.com/TheEightBot/Xamarin.IQKeyboardManager/tree/master/IQKeyboardManager.Sample

But in general you need to add a reference to the IQKeyboardManager.dll to your project. And configure it in the ViewDidLoad method. For example:

``` csharp
public override void ViewDidLoad ()
{
    base.ViewDidLoad ();

    Xamarin.IQKeyboardManager.SharedManager.EnableAutoToolbar = true;
    Xamarin.IQKeyboardManager.SharedManager.ShouldResignOnTouchOutside = true;
}
```

**Comment by squeaky-nose** [comment]
Seems the sample doesnt compile with latest visual studio. Any idea whats up?

**Comment by michaelstonis** [comment]
I am not sure that iOS bindings projects will compile in Visual Studio. I have not verified this, but that was at least the case for a good long time.
