### ISSUE TITLE
isAskingCanBecomeFirstResponder category access

### ISSUE THREAD

**Issue by javalnanda** [TheEightBot/Xamarin.IQKeyboardManager#3]
How can we use isAskingCanBecomeFirstResponder property in xamarin that is available in category in the IQKeyboardManager native library?

**Comment by michaelstonis** [comment]
@javalnanda it looks like the binding might need to be migrated to a Category instead of a Protocol to get these to generate as extension methods. I will look into updating this.

**Comment by javalnanda** [comment]
@michaelstonis That would be great to have this as a part of new update.

**Comment by michaelstonis** [comment]
We modified the library and added the extensions methods for all of the UIView and UIViewController components.
