### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by squeaky-nose** [TheEightBot/Xamarin.IQKeyboardManager#4]
When i import the Xamarin.IQKeyboardManager project i get this error...

System.IO.FileNotFoundException: /Users/cimacminiserver/Library/Caches/Xamarin/mtbs/builds/testApp/f6ad86a48dd1368f2f69ab2b6c25b109/obj/iPhone/Debug/IQKeyboardManager.bundle/IQButtonBarArrowLeft@2x.png does not exist.

Seems its not being extracted correctly. Notice the "\" in the filename of the bundle contents...

CIs-Mac-mini:Debug cimacminiserver$ pwd
/Users/cimacminiserver/Library/Caches/Xamarin/mtbs/builds/testApp/f6ad86a48dd1368f2f69ab2b6c25b109/obj/iPhone/Debug

CIs-Mac-mini:Debug cimacminiserver$ ls
IQKeyboardManager.bundle\IQButtonBarArrowLeft@2x.png
IQKeyboardManager.bundle\IQButtonBarArrowRight@2x.png
IQKeyboardManager.bundle\de.lproj\IQKeyboardManager.strings
IQKeyboardManager.bundle\en.lproj\IQKeyboardManager.strings
IQKeyboardManager.bundle\es.lproj\IQKeyboardManager.strings
IQKeyboardManager.bundle\zh-Hans\IQKeyboardManager.strings
IQKeyboardManager.bundle\zh-Hant\IQKeyboardManager.strings
actool
ibtool
ibtool-manifests
optimized

**Comment by michaelstonis** [comment]
@sushant40 are you building this from Xamarin Studio directly or using a CI server and command line? I just tried building and using the solution from source on a mac with Xamarin Studio and it seemed alright.

**Comment by arotolo** [comment]
@sushant40 I'm not sure of a permanent fix, but try cleaning your Xamarin.iOS project and deleting the "bin" and "obj" directories. That's worked for me in the past.
