### ISSUE TITLE
Previous/Next not showing on iOS 9.3.2

### ISSUE THREAD

**Issue by javal-idyllic** [TheEightBot/Xamarin.IQKeyboardManager#5]
Previous and Next image not showing on iOS 9.3.2 but they are clickable. Not sure if the issue is with this binding or on the original IQKeyboardManager also.

**Comment by michaelstonis** [comment]
We just updated the library to sync up with version 4.0.8, it was tested on latest iOS and seems to display all arrows appropriately.
