### ISSUE TITLE
_IQDescription unrecognized selector

### ISSUE THREAD

**Issue by KennethKr** [TheEightBot/Xamarin.IQKeyboardManager#6]
Hi.

I get the following error and crash using Xamarin.IQKeyboardManager:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UITextField _IQDescription]: unrecognized selector sent to instance 0x157baa890

`IQKeyboardManager.IQKeyboardManager.SharedManager.EnableAutoToolbar = true;
            IQKeyboardManager.IQKeyboardManager.SharedManager.ShouldResignOnTouchOutside = true;`

The only IQ-related code in my code is the above code. I've installed it using nuget.

**Comment by elpendor** [comment]
I'm having the same issue here.

Installed through Nuget as well.

**Comment by michaelstonis** [comment]
I am not sure how the nuget release is implemented. That is a totally separate project. This particular version has to be built from source and included in your project.

**Comment by elpendor** [comment]
The problem is also present when is built from source.

**Comment by elpendor** [comment]
Nevermind. Cleaned the project and added the compiled assembly and it worked.

It's probably a problem with the nuget project as you said.
