### ISSUE TITLE
[question] how to do cross-platform keyboard handling for Xamarin.Forms ?

### ISSUE THREAD

**Issue by dodikk** [TheEightBot/Xamarin.IQKeyboardManager#7]
I've been usign this Obj-C library and I'd like to have similar experience in a cross-platform project.
Unfortunately, I have not managed to find any component that handles Xamarin.Forms in this manner.

Are there any worthy competitors or PCL wrappers around?

P.S. Sorry if this is a wrong place to ask.

**Comment by michaelstonis** [comment]
There is nothing that I know about that would work x-platform. Android and UWP have built-in keyboard management in them which already do essentially what this component is doing. Xamarin.Forms also has some built-in tap gestures and autoducking, but it is not exactly the same. FWIW, if you are using Xamarin.Forms, the best advice I would give is to wrap your controls with ScrollViews. This will ensure that the UI can scroll appropriately out of the way, if there is a keyboard that needs to be displayed.
