### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by rusty21** [TheEightBot/Xamarin.IQKeyboardManager#8]
Could we get an update for this, there seems to be some missing functionality that I would like to take advantage of.

**Comment by michaelstonis** [comment]
Can you expand on that? I believe the current release of this package is only one release behind and that release is only for swift support.

**Comment by rusty21** [comment]
Maybe it's just my lack of knowledge but I want to use the previous next functionality for the tool bar, but my text fields don't have the same direct parent. I was hoping to use this property
`@property(nonatomic, strong, nonnull, readonly) NSMutableSet<Class> *toolbarPreviousNextAllowedClasses;` to allow the previous next functionality to work with textfields that are in different subviews. I don't see this property as an option in this library.

**Comment by rusty21** [comment]
Is there an update on this?

**Comment by michaelstonis** [comment]
I updated the package with the latest API definitions from 4.0.9. This should include the functionality that you are looking for.

**Comment by rusty21** [comment]
Thanks I appreciate it!
